name: "Linting"

on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  pylint:
    name: Python Code Quality and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter-env: ["linting", "type_check", "spell_check"]
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: "3.14"
      - name: Run ${{ matrix.linter-env }}
        run: |
          case "${{ matrix.linter-env }}" in
            linting)
              uv run --group linting pylint bnetza_bk6_scraper
              uv run --group linting pylint unittests --rcfile=unittests/.pylintrc
              ;;
            type_check)
              uv run --group type_check mypy --show-error-codes src/bnetza_bk6_scraper --strict
              uv run --group type_check mypy --show-error-codes unittests --strict
              ;;
            spell_check)
              uv run --group spell_check codespell --ignore-words=domain-specific-terms.txt src
              uv run --group spell_check codespell --ignore-words=domain-specific-terms.txt README.md
              ;;
          esac
